config/routes.rb
Rails.application.routes.draw do
  get 'sitemap.xml' => 'sitemap#xml', defaults: { format: :xml }

  get 'user/:user_id' => 'public#user', as: 'user'

  get 'user/:user_id/screenshots/:screenshot_id' => 'public#user_screenshots_view', as: 'user_screenshot'
  get 'user/:user_id/screenshots' => 'public#user_screenshots_list', as: 'user_screenshots'

  get 'clip/:clip_id' => 'public#clip', as: 'clip'
  get 'clip/:clip_id/twitter_container' => 'public#clip_twitter_container', as: 'twitter_player_container'
  get 'game/:game_id' => 'public#game', as: 'game'

  post 'clip/:clip_id/vote' => 'public#vote', as: 'vote'

  get 'popular' => 'public#popular', as: 'popular'

  get 'home' => 'public#home', as: 'home'
  get 'users' => 'public#users', as: 'users'
  get 'games' => 'public#games', as: 'games'

  root 'public#home'

  get 'dashboard' => 'dashboard#index', as: 'dashboard'
  get 'profile' => 'dashboard#profile'
  post 'profile' => 'dashboard#profile_post', as: 'profile_post'

  get 'feed/twitter', defaults: { format: :xml }, as: 'twitter_feed'

  get 'faq' => 'public#faq', as: 'faq'

  devise_for :users

  namespace :api do
    namespace :v1 do
      get 'videos/firehose'
      get 'videos/mine'
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!

  def index
    if current_user.gamertag.nil?
      redirect_to profile_path
      return
    end

    @videos = current_user.videos.uploaded.order('recorded_at DESC')
  end

  def profile

  end

  def profile_post
    gamertag = params[:gamertag]

    current_user.update_attributes(:gamertag => gamertag)

    FetchClipsWorker.perform_async(current_user.id)

    redirect_to root_path
  end
end

app/views/dashboard/index.html.erb
<% if @videos.count > 0 %>
  <ul class="videos-grid">
    <% @videos.each do |video| %>
      <li>
        <a href="<%= clip_path(video.clip_id) %>">
          <img src="<%= video.thumbnail_large %>" />
        </a>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>
    You don't have any videos yet.
  </p>
<% end %>

app/views/dashboard/profile.html.erb
<header class="hero">
  <h1>Profile</h1>
</header>

<h2>About You</h2>

<p>
  You have been a member since <%= current_user.created_at.strftime("%d %b %G") %>, have uploaded <%= current_user.videos.count %> clips,
  have accumulated <%= pluralize current_user.videos.sum(:view_count), 'view' %> and <%= pluralize current_user.videos.sum(:like_count), 'like' %>.
</p>
<br />
<p>
  <% if current_user.is_pro? %>
    You are a
  <% else %>
    You are not a
  <% end %>
  <span class="badge pro">pro</span> user.
</p>

<form class="central" action="<%= profile_post_path %>" method="post" onsubmit="return confirm('Are you sure this is your gamertag?')">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

  <div>
    <label for="gamertag">Xbox Live Gamertag</label>
    <input type="text" name="gamertag" value="<%= current_user.gamertag %>" />
  </div>

  <input type="submit" value="Save" />
</form>

app/views/dashboard/settings.html.erb
<h1>Settings</h1>

<p>
  <strong>Note:</strong> Videos are not downloaded in real-time, there will be a delay.  Also, make sure that your privacy settings
  allow anyone to see the videos you create.
</p>

<form action="<%= settings_post_path %>" method="post" onsubmit="return confirm('Are you sure this is your gamertag?')">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

  <label for="gamertag">Xbox Live Gamertag</label>
  <input type="text" name="gamertag" value="<%= current_user.gamertag %>" />

  <input type="submit" value="Save" />
</form>