config/routes.rb
Rails.application.routes.draw do
  get 'sitemap.xml' => 'sitemap#xml', defaults: { format: :xml }

  get 'user/:user_id' => 'public#user', as: 'user'

  get 'user/:user_id/screenshots/:screenshot_id' => 'public#user_screenshots_view', as: 'user_screenshot'
  get 'user/:user_id/screenshots' => 'public#user_screenshots_list', as: 'user_screenshots'

  get 'clip/:clip_id' => 'public#clip', as: 'clip'
  get 'clip/:clip_id/twitter_container' => 'public#clip_twitter_container', as: 'twitter_player_container'
  get 'game/:game_id' => 'public#game', as: 'game'

  post 'clip/:clip_id/vote' => 'public#vote', as: 'vote'

  get 'popular' => 'public#popular', as: 'popular'

  get 'home' => 'public#home', as: 'home'
  get 'users' => 'public#users', as: 'users'
  get 'games' => 'public#games', as: 'games'

  root 'public#home'

  get 'dashboard' => 'dashboard#index', as: 'dashboard'
  get 'profile' => 'dashboard#profile'
  post 'profile' => 'dashboard#profile_post', as: 'profile_post'

  get 'feed/twitter', defaults: { format: :xml }, as: 'twitter_feed'

  get 'faq' => 'public#faq', as: 'faq'

  devise_for :users

  namespace :api do
    namespace :v1 do
      get 'videos/firehose'
      get 'videos/mine'
    end
  end

end

app/views/shared/_game.html.erb
<div class="col-md-<%= width %>">
    <div class="game game-<%= type %>">
        <a href="<%= game_path(game.xgid) %>" style="background-image: url(<%= game.image_box %>)"><%= game.name %></a>
    </div>
</div>

app/views/shared/_gamerpane.erb
<div class="gamerpane">
  <!--
  <a href=""><img src="https://pbs.twimg.com/profile_images/448105818466963457/tQsf_zqs_400x400.jpeg" /></a>
  -->
  <a href="<%= user_path(user.gamertag) %>"><%= user.gamertag %></a>
  <!--
  <p>
      <span class="i-score">g</span> 40,300
  </p>
  -->
  <p class="stats">
      <%= user.videos.count %> clips, <%= user.total_views %> views
  </p>
</div>

app/views/shared/_screenshot.erb
<div class="col-md-<%= width %>">
    <div class="screenshot screenshot-<%= type %>">
        <a href="<%= user_screenshot_path(screenshot.user.gamertag, screenshot.xuid) %>"><img src="<%= ImageHelper.resized(screenshot.cdn_url, 375) %>" /></a>
    </div>
</div>

app/views/shared/_video.html.erb
<% can_play = defined? playable and playable %>

<div class="col-md-<%= width %>">
    <div class="video video-<%= type %>">
        <% if can_play %>
            <video controls autoplay id="video" class="video-js vjs-default-skin" width="auto" height="auto" poster="<%= video.cdn_thumbnail_url %>" >
                <source type="video/mp4" src="<%= @video.cdn_clip_url %>">
                <source type="rtmp/mp4" src="<%= @video.cdn_rtmp_original_url %>">
            </video>
        <% else %>
            <div class="poster" style="background-image: url('<%= video.cdn_thumbnail_url %>')">
                <a href="<%= clip_path(video.clip_id) %>" class="play"><span>Play</span></a>
                <div class="accent"></div>
            </div>
        <% end %>

        <div class="description">
            <span class="title"><%= link_to video.user.gamertag, user_path(video.user.gamertag) %> playing <%= link_to(video.game.name, game_path(video.game.xgid)) %></span>
            <span class="subtitle" data-livestamp="<%= video.recorded_at.to_i %>"><%= video.recorded_at %></span>
        </div>
    </div>
</div>

<% if can_play %>
    <script type="text/javascript">
        $(function () {
            videojs("video", {
                techOrder: ["flash", "html5"],
                poster: "<%= video.cdn_thumbnail_url %>",
                controls: true,
                preload: true
            }, function(){

            });
        });
    </script>
<% end %>