config/routes.rb
Rails.application.routes.draw do
  get 'sitemap.xml' => 'sitemap#xml', defaults: { format: :xml }

  get 'user/:user_id' => 'public#user', as: 'user'

  get 'user/:user_id/screenshots/:screenshot_id' => 'public#user_screenshots_view', as: 'user_screenshot'
  get 'user/:user_id/screenshots' => 'public#user_screenshots_list', as: 'user_screenshots'

  get 'clip/:clip_id' => 'public#clip', as: 'clip'
  get 'clip/:clip_id/twitter_container' => 'public#clip_twitter_container', as: 'twitter_player_container'
  get 'game/:game_id' => 'public#game', as: 'game'

  post 'clip/:clip_id/vote' => 'public#vote', as: 'vote'

  get 'popular' => 'public#popular', as: 'popular'

  get 'home' => 'public#home', as: 'home'
  get 'users' => 'public#users', as: 'users'
  get 'games' => 'public#games', as: 'games'

  root 'public#home'

  get 'dashboard' => 'dashboard#index', as: 'dashboard'
  get 'profile' => 'dashboard#profile'
  post 'profile' => 'dashboard#profile_post', as: 'profile_post'

  get 'feed/twitter', defaults: { format: :xml }, as: 'twitter_feed'

  get 'faq' => 'public#faq', as: 'faq'

  devise_for :users

  namespace :api do
    namespace :v1 do
      get 'videos/firehose'
      get 'videos/mine'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= render 'global/head' %>
    <%= yield(:additional_head) %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="dns-prefetch" href="//d3s9v1x1919qoo.cloudfront.net">
    <link rel="dns-prefetch" href="//s16osvqw5sdzqt.cloudfront.net">

    <script>
        videojs.options.flash.swf = "<%= ActionController::Base.helpers.asset_path "video-js.swf" %>";
    </script>

</head>
<body data-no-turbolink>
    <div class="container-fluid container-body">
        <header class="row header-row">
            <div class="col-md-8">
                <a href="<%= root_path %>"><h1 class="logo"><span>xb</span>vids</h1></a>
                <p class="tagline">
                    The easiest way to share your Xbox One gameclips and screenshots with the world.
                </p>
            </div>
            <div class="col-md-4">
                <% unless user_signed_in? %>
                    <a class="cta-signup" href="<%= new_user_registration_path %>">
                        <p>
                            Create an account to add your game clips and start sharing them
                        </p>
                        <h2>Sign up</h2>
                    </a>
                <% end %>
            </div>
        </header>

        <div class="row menu-row">
            <div class="col-md-12">
                <ul class="menu">
                    <li><a href="<%= root_path %>">Featured</a></li>
                    <li><a href="<%= games_path %>">Games</a></li>
                    <li><a href="<%= users_path %>">Players</a></li>
                    <li class="spacer">•</li>
                    <% if user_signed_in? %>
                        <li>
                            <%= link_to current_user.gamertag, user_path(current_user.gamertag) %>
                        </li>
                        <li>
                            <%= link_to "Log out?", destroy_user_session_path, :method => :delete, :data => { :confirm => 'Are you sure you want to log out?' } %>
                        </li>
                    <% else %>
                        <li><a href="<%= new_user_session_path %>">Log in</a></li>
                    <% end %>
                </ul>
            </div>
        </div>

		<div class="page-width">
        	<%= yield %>
        </div>

    </div>

    <div class="container-fluid container-footer">
        <div class="row vgutter-row">
            <div class="col-md-6">
                <ul class="menu">
                    <li><a href="<%= root_path %>">Featured</a></li>
                    <li><a href="<%= games_path %>">Games</a></li>
                    <li><a href="<%= users_path %>">Players</a></li>
                    <li class="spacer">•</li>
                    <% if user_signed_in? %>
                        <li>
                            <%= link_to current_user.gamertag, user_path(current_user.gamertag) %>
                        </li>
                        <li>
                            <%= link_to "Log out?", destroy_user_session_path, :method => :delete, :data => { :confirm => 'Are you sure you want to log out?' } %>
                        </li>
                    <% else %>
                        <li><a href="<%= new_user_session_path %>">Log in</a></li>
                    <% end %>
                </ul>
            </div>
            <div class="col-md-6">

            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <a href="<%= root_path %>"><h1 class="logo"><span>xb</span>vids</h1></a>
                <p class="tagline">
                    The easiest way to share your Xbox One gameclips and screenshots with the world.
                </p>
            </div>
            <div class="col-md-6">
                <p class="impressum">
                    Made by <a href="https://twitter.com/nickj89">@nickj89</a>.
                </p>
            </div>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <%= render 'global/ga' %>
    <%= yield(:additional_footer) %>

</body>
</html>